Repository GllO-2025/GllO-Flutter, pull requests merged in 2025-07, with the labels that each got.

#19 [FEAT] Page Indicator 추가
  lib/design_system/component/app_page_indicator.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎨 ui

#21 [FEAT] 아이콘 추가
  asset/icon/media/pic_fill.svg
  asset/icon/media/video.svg
  asset/icon/quick_action/check_fill.svg
  asset/icon/quick_action/comment_2_fill.svg
  asset/icon/quick_action/send_fill.svg
  asset/icon/quick_action/share_forward_fill.svg
  asset/icon/system/cancel.svg
  asset/icon/system/check_circle_fill.svg
  asset/icon/system/replay.svg
  asset/icon/system/settings_3_line.svg
  asset/icon/system/warning_line.svg
  lib/app/asset/assets.gen.dart
  lib/design_system/component/app_navigation_bar.dart
  lib/design_system/component/app_segment_control.dart
  lib/design_system/component/app_tab.dart
Labels: ➕ add

#32 [FEAT] App Gradient Overlay 추가
  lib/design_system/component/app_gradient_overlay.dart
Labels: 🎨 ui

#28 [FEAT] App Bar 추가
  lib/design_system/component/base_app_bar.dart
  lib/design_system/component/svg_action_icon.dart
Labels: 🎨 ui

#22 [FEAT] Snack Bar, Toast 추가
  ios/Podfile.lock
  lib/app/router/app_router.dart
  lib/app/toast/toast_manager.dart
  lib/design_system/component/app_snack_bar.dart
  lib/design_system/component/app_toast.dart
  lib/presentation/app.dart
  pubspec.lock
  pubspec.yaml
Labels: 🎨 ui

#23 [FEAT] Loading UI 추가
  asset/animation/loading1.json
  lib/app/asset/assets.gen.dart
  lib/design_system/component/app_loading.dart
Labels: 🎨 ui

#30 [FEAT] App Text Area Field
  lib/design_system/component/app_text_area_field.dart
Labels: 🎨 ui

#25 [FEAT] Chip, Tag 추가
  lib/design_system/component/app_chip.dart
  lib/design_system/component/app_tag.dart
Labels: 🎨 ui

#27 [FEAT] App Dropdown 추가
  lib/design_system/component/app_dropdown.dart
Labels: 🎨 ui

#29 [FEAT] App Input Field 추가
  lib/design_system/component/app_form_input_field.dart
  lib/design_system/component/app_input_field.dart
  lib/design_system/component/app_input_status.dart
Labels: 🎨 ui

#34 [FEAT] 다국어 지원을 위한 구조 생성
  asset/translation/en-US.json
  asset/translation/ko-KR.json
  devtools_options.yaml
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/app/asset/assets.gen.dart
  lib/app/entrypoint/main.dart
  lib/app/environment/environment.dart
  lib/app/localization/check_locale_keys.dart
  lib/app/localization/locale_keys.g.dart
  lib/app/localization/localization.dart
  lib/app/localization/localization_enum.dart
  lib/design_system/component/app_navigation_bar.dart
  lib/design_system/component/app_search_bar.dart
  lib/design_system/component/app_text_area_field.dart
  lib/presentation/app.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ feature, ➕ add
